// <auto-generated />
using System;
using Kamus.Inventory.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kamus.Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20261006124451_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kamus.Inventory.Domain.StockLevel", b =>
                {
                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("SkuId")
                        .HasName("pk_stock_levels");

                    b.ToTable("stock_levels", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_stock_levels_quantity", "quantity >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
