<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../../shared/Kamus.Shared/Kamus.Shared.csproj" />
    <ProjectReference Include="../Kamus.Inventory.Contracts/Kamus.Inventory.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kamus.IntegrationTests" />
  </ItemGroup>

</Project>
