<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../../shared/Kamus.Shared/Kamus.Shared.csproj" />
    <ProjectReference Include="../Kamus.Identity.Contracts/Kamus.Identity.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kamus.IntegrationTests" />
  </ItemGroup>

</Project>
