<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/modules/Orders/Kamus.Orders/Kamus.Orders.csproj" />
    <ProjectReference Include="../../src/modules/Payments/Kamus.Payments/Kamus.Payments.csproj" />
    <ProjectReference Include="../../src/shared/Kamus.Shared/Kamus.Shared.csproj" />
  </ItemGroup>

</Project>
